diary/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :users
    resources :entries
  root 'entries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

diary/app/models/entry.rb
class Entry < ApplicationRecord
  validates :date, presence: true, length: {maximum: 10}
end

diary/app/models/user.rb
class User < ApplicationRecord
end

diary/app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def new
  end

  def create
    @entry = Entry.new(diary_params)

    if @entry.save
      redirect_to @entry
    else
      render 'new' #issue same request, the same article object is passed again
      #redirect_to new request is issued.
    end

  end

  def update
    @entry = Entry.find(params[:id])

    if @entry.update(diary_params)
      redirect_to @entry
    else
      render 'edit'
    end
  end

  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to entries_path
  end
  
  private

  def diary_params
    params.require(:entry).permit(:date, :note)
  end


end

diary/app/controllers/users_controller.rb
class UsersController < ApplicationController
end

diary/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

diary/app/helpers/entries_helper.rb
module EntriesHelper
end

diary/app/helpers/users_helper.rb
module UsersHelper
end

diary/app/helpers/welcome_helper.rb
module WelcomeHelper
end

diary/app/views/entries/edit.html.erb
<h1>Edit entry</h1>
<%= simple_form_for Entry.find(params[:id]) do |f| %>
<%= f.input :date, placeholder: 'dd/mm/yyyy' %>
<%= f.input :note %>
<%= f.button :submit %>
<% end %>
<%= link_to 'Back', entries_path %>

diary/app/views/entries/index.html.erb
<h1>Diary</h1>
<table class="table-responsive table-striped table-bordered" style="border:1px;">
  <tr>
    <td>Date</td>
    <td>Log</td>
    <td>Action</td>
  </tr>
  <% @entries.each do |entry| %>
    <tr>
      <td><%= entry.date %></td>
      <td><%= entry.note %></td>
      <td><%= link_to 'Show', entry_path(entry) %>
        <%= link_to 'Edit', edit_entry_path(entry) %>
        <%= link_to 'Delete', entry_path(entry), method: :delete,
        data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
</table>

diary/app/views/entries/new.html.erb
<h1>New entry</h1>
<div class="container">
<%= simple_form_for Entry.new do |f| %>
<div class="form-group">
<%= f.input :date, placeholder: 'dd/mm/yyyy', error: 'Date is mandatory', class: 'form-control' %>
</div>
<div class="form-group">
<%= f.input :note, label: 'Diary entry' %>
</div>
<%= f.button :submit %>
<% end %>
</div>
<%= link_to 'Back', entries_path%>

diary/app/views/entries/show.html.erb
<h1>Diary log for <%= @entry.date %> </h1>
<p><%= @entry.note %></p>
<%= link_to 'Back', entries_path %>

diary/app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse navbar-fixed-top">
  <%= link_to "Diary", entries_path, class: "navbar-brand" %>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <%= link_to "New entry", new_entry_path %>
    </li>

  </ul>
</nav>

diary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Old+Standard+TT' rel='stylesheet' type='text/css'>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">

    <%= yield %>
  </div>
  </body>
</html>

diary/app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>Diary app!</p>